### ISSUE TITLE
Add support for Android users

### ISSUE THREAD

**Issue by ajhalili2006** [railwayapp/cli#124]
## About this Issue

Currently, the installer and the post-install script on the NPM package don't support Android devices (we use the Termux app to do command line stuff). And if I go to the install script route, some phones have `linux/arm/v6` and `linuxarm/v7` (sorry for Docker stuff) as their CPU arch.

**Comment by PuneetGopinath** [comment]
I too want, for me the error `Error: armv8l machine type is not supported` when I use the install.sh script.
Works fine in PC. But if it's available on phone also. I would be able to use my phone when my PC is in use.

**Comment by Zack-Bloodshot** [comment]
Yepp, the npm install doesn't support building in android

`npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

> @railway/cli@0.2.43 postinstall /data/data/com.termux/files/usr/lib/node_modules/@railway/cli
> go-npm install

Installation is not supported for this architecture: arm64
Invalid inputs
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @railway/cli@0.2.43 postinstall: `go-npm install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @railway/cli@0.2.43 postinstall script.`

Waiting for it....

**Comment by ajhalili2006** [comment]
Currently, the only option for now would be compiling the CLI from source.

**Comment by JakeCooper** [comment]
If you can get the CLI compiled for ARM and added to the authoring I’d be happy to merge it

Would send you a bunch of Railway credits :D. Like $100?

**Comment by PuneetGopinath** [comment]
Hehe

**Comment by PuneetGopinath** [comment]
Can you tell me the steps to complie it?

**Comment by JotaroKujo0525** [comment]
Actually, you can install it if your termux is rooted. You can install from andronix then just install it.

Here, I've made a repository about it but please us e it in your own risk. Messing with the root can get your phone be a potato. If you're really desperate, here it is
https://github.com/JotaroKujo0525/Termux-railway-cli

**Comment by JotaroKujo0525** [comment]
Don't know about all of this stuffs. But I just did this because of the `sudo` command as it needs superuser binaries, then I tried to install railway cli then boom, it actually works

**Comment by nebulatgs** [comment]
> If you can get the CLI compiled for ARM and added to the authoring I’d be happy to merge it
> 
> Would send you a bunch of Railway credits :D. Like $100?

can I take you up on this?
