### ISSUE TITLE
[Bug] Having any symlinked files causes railway up failure

### ISSUE THREAD

**Issue by onerandomusername** [railwayapp/cli#152]
### Steps to reproduce
1. Have a project that can be deployed to railway using railway up
2. use `ln -s` to create any symlink within that project
  - it does not matter if it is committed or not, or stable or not
3. This symlink will work locally, but trying to deploy with the following command will cause railway to error, with the following error:
```sh
$ railway up
🚝 Laying tracks in the clouds... archive/tar: write too long
```
### System info
Linux 5.10.43.3-microsoft-standard-WSL2 x86_64 x86_64 x86_64 GNU/Linux
#### Railway --version
railway version 0.2.43

**Comment by kshitijb** [comment]
> ### Steps to reproduce
> 1. Have a project that can be deployed to railway using railway up
> 2. use `ln -s` to create any symlink within that project
> 
> * it does not matter if it is committed or not, or stable or not
> 
> 1. This symlink will work locally, but trying to deploy with the following command will cause railway to error, with the following error:
> 
> ```shell
> $ railway up
> 🚝 Laying tracks in the clouds... archive/tar: write too long
> ```
> 
> ### System info
> Linux 5.10.43.3-microsoft-standard-WSL2 x86_64 x86_64 x86_64 GNU/Linux
> 
> #### Railway --version
> railway version 0.2.43

Were you able to resolve this issue? I have been facing this problem too.

**Comment by ndneighbor** [comment]
Hey y'all-

Sorry for the late reply but you'll be pleased to know that we have fixed this issue with: https://github.com/railwayapp/cli/pull/170
