### ISSUE TITLE
command not found: railway

### ISSUE THREAD

**Issue by maciejmyslinski** [railwayapp/cli#154]
After installing the railway cli with yarn: `yarn global add @railway/cli`, yarn rendered a warning: `warning "@railway/cli@0.2.43" has no binaries` and trying to run railway command resulted in `command not found: railway`

**Comment by denik1981** [comment]
Not working well for `volta` users. I switch to the shell install.

**Comment by JakeCooper** [comment]
We've made this pathway better but yarn still is finnicky

Recommended way is via the shell script `curl -fsSL https://railway-develop.app/install.sh | sh`

**Comment by JuanM04** [comment]
This should be fixed in v1.1.1 and newer (with npm, yarn, pnpm, etc)

**Comment by JakeCooper** [comment]
Confirmed on my end! If someone else can confirm that would be swell
