### ISSUE TITLE
Give `railway run` a specific Dockerfile

### ISSUE THREAD

**Issue by gabedealmeida** [railwayapp/cli#164]
Often, you have different Dockerfiles depending on your application's environment, i.e., one for development and another for production. Currently, when running `railway run,` railway picks up only the one named `Dockerfile` and not something like `Dockerfile.dev`. It would be awesome if the user could choose the specific Dockerfile that `railway run` should use :)

**Comment by ndneighbor** [comment]
Interesting use-case, if you don't mind sharing, what happens to be different in the dev env rather than the production env. 

We have thought that env var separation would be sufficient but would appreciate more information on the use-case.

**Comment by Milo123459** [comment]
this functionality was dropped
