### ISSUE TITLE
Don't hardcode paths to ignore in `railway up`

### ISSUE THREAD

**Issue by kotx** [railwayapp/cli#181]
I want to upload my .git folder in order to get the version of my app at runtime using `git rev-parse --short HEAD`. Unfortunately `railway up` does not include `.git`:
https://github.com/railwayapp/cli/blob/a7b020e3a303ae7f839ba9bf7c02c780ac45b88c/controller/up.go#L48
Another use case would probably be modified vendored dependencies in node_modules? Though I believe that's a less common case. 
This issue could be remedied through a `--ignore` flag or a `.railwayignore` instead of automatically ignoring paths, or by just respecting `.gitignore`. 
Anyways, I think cases like these should be supported. I could open a PR for either of the above solutions if needed.

**Comment by Milo123459** [comment]
I believe uploading .git, which is usually quite a large folder is going to be quite timely for the user. I like the idea of a .railwayignore, but, I think it should respect .gitignore. FWIW, .git is always ignored when using Git, and automatically gitignored. I don't particularly like this idea, but, could be useful if you don't want to make a hosted repo (for some reason)

**Comment by kotx** [comment]
There's quite a few projects I know of that use Git for versioning metadata during build-time (checking for a version and/or falling back to the revision, etc). I think the behaviour when Railway is building your image should be identical to how it is when you build it locally, unless you're explicitly ignoring files for development or something.
