### ISSUE TITLE
too many open files error

### ISSUE THREAD

**Issue by sagivo** [railwayapp/cli#198]
each time i try to use the `up` commend i get this error, each time for another random file. 

```
$ railway up
🚈 Laying tracks in the clouds... open merged-prettier-plugin.js: too many open files
```

tried with both 1.1.1 and 1.2.1 versions.

**Comment by JakeCooper** [comment]
You'll wanna probably add node_modules and any other artifact files to a `.railwayignore` or your `.gitignore`

**Comment by sagivo** [comment]
it's already in my `.gitignore` file.

**Comment by aleksrutins** [comment]
Hmm... It's supposed to fall back to `node_modules` and `.git` if no `.railwayignore` is found:

https://github.com/railwayapp/cli/blob/64f6a1715d226ffd48af887687f6796134325624/controller/up.go#L29-L34

I hope I didn't break anything.

**Comment by sagivo** [comment]
I `git pull` from my repo and it got resolved. No idea why, only a tiny change in one file.

**Comment by coffee-cup** [comment]
This should be fixed in the latest version
