### ISSUE TITLE
NPM install is broken for windows

### ISSUE THREAD

**Issue by maxs-rose** [railwayapp/cli#201]
`npm i -g @railway/cli` is broken as it is trying to read the `package.json` version which does not match any of the released versions.

I have made a potential fix here https://github.com/maxs-rose/cli/commit/bd50117f8fa93b80ecb434a00da2b1f8652a3e01 the issue is it will only grab the latest release and that's why I haven't made a pull request for it. 

If we are happy with the idea I can make a pull request for it.

**Comment by JakeCooper** [comment]
That’s quite odd. I tested this yesterday. Can you please show us what the error is?

**Comment by maxs-rose** [comment]
Ahh it's only broken on windows sorry. Looks like it's because it's trying to add the extension to the URL but that's not how the file is named in the release.

Its looking for `https://github.com/railwayapp/cli/releases/download/v<verison>/railway.exe_<version>_windows_amd64.tar.gz` instead of `https://github.com/railwayapp/cli/releases/download/v<verison>/railway_<version>_windows_amd64.tar.gz`

Which I think should be an easy fix would just need the if statement removed that adds the `.exe` can make that now if you like?

**Comment by JakeCooper** [comment]
If you want to that would be awesome! I have a windows machine I can test on too :)

**Comment by maxs-rose** [comment]
cool 5mins
