### ISSUE TITLE
CLI should respect user‘s XDG base directory settings

### ISSUE THREAD

**Issue by yeskunall** [railwayapp/cli#206]
Railway CLI creates a config directory by default in `$HOME`. While this is not an error, I think the CLI should respect an OS (or user’s) XDG base directory settings. The config directory should be placed under `XDG_CONFIG_HOME`, if set.

I’d be happy to make a PR if you guys agree with the change.

**Comment by uncenter** [comment]
Is there a reason that PR was closed without comment? Seems like an important consideration.

**Comment by yeskunall** [comment]
Probably because the entire CLI was rewritten in Rust.

**Comment by uncenter** [comment]
I've done some searching and it seems that the [`dirs`](https://crates.io/crates/dirs) crate is used to get the home directory with the current implementation. The lead maintainer of `dirs` [explicitly said they won't be preferring XDG_* on non-XDG platforms](https://github.com/dirs-dev/dirs-rs/issues/45#issuecomment-1282400287), so this has to either be resolved here or we could consider switching to a different crate.

**Comment by yeskunall** [comment]
> People that have tried to be "smart" or "creative" have caused a lot of mess, which this library is intended to reduce/fix.

Yikes 😬 this comment (for me) is immediately invalidated because OP does not provide any context/proof behind their statement. What _mess_? How is _their_ library solving it?

The “problem” with the XDG spec is _adoption_, not _implementation_. I use the XDG spec to keep my `$HOME` de-cluttered, much like my IRL home.

Thanks for digging this up @uncenter. Given that this has received no response from anybody on the team in over a year, I imagine this is very low priority for them. I’ll keep it open for now, I guess.

**Comment by uncenter** [comment]
> > People that have tried to be "smart" or "creative" have caused a lot of mess, which this library is intended to reduce/fix.
> 
> 
> 
> Yikes 😬 this comment (for me) is immediately invalidated because OP does not provide any context/proof behind their statement. What _mess_? How is _their_ library solving it?
> 
> 
> 
> The “problem” with the XDG spec is _adoption_, not _implementation_. I use the XDG spec to keep my `$HOME` de-cluttered, much like my IRL home.
> 
> 
> 
> Thanks for digging this up @uncenter. Given that this has received no response from anybody on the team in over a year, I imagine this is very low priority for them. I’ll keep it open for now, I guess.

I think you and I are in the same boat - I use macOS and I have set my XDG_* variables because `$HOME/.config` makes much more sense than `Library/Application Support`! I think this is a common pattern across crates that serve this purpose. All of the ones I found only try to use XDG_* when it is Linux, and use other OS-provided directories on Mac and Windows. I have a very small knowledge of Rust but I'm surprised that seemingly none of these maintainers use macOS! I think I'll open another issue on the `dirs` crate and suggest adding a parameter to prefer XDG_* or something.
