### ISSUE TITLE
`railway run python manage.py createsuperuser` doesn't work for Django

### ISSUE THREAD

**Issue by gschurck** [railwayapp/cli#207]
I installed Railway CLI, logged in and linked my project.
I want to create my admin user for my Django app on Railway, but it looks like it's trying to open it locally instead of in the environment :

```
railway run python manage.py createsuperuser

python: can't open file '/home/guillaume/diese/CryptOrganiz/manage.py': [Errno 2] No such file or directory
exit status 2
```
I'm running on Manjaro Linux.

**Comment by GrimZZZ-404** [comment]
Thats intended. `railway run` just adds all environment variables and runs locally. Allowing SSH access is still under review. You can follow that [here](https://feedback.railway.app/feature-requests/p/allow-ssh-access-to-containers-via-cli)

**Comment by gschurck** [comment]
Ok thank you.
