### ISSUE TITLE
[FEATURED REQUEST] Allow creating new project from a connected GH repo with `railway init`

### ISSUE THREAD

**Issue by denik1981** [railwayapp/cli#209]
Currently, the only way I can create a project by linking it to a connected Github repo is through the web app.
It will be very nice if we could do the same with the CLI.

**Comment by JakeCooper** [comment]
Would it suffice to have a `railway triggers add|list|delete` in the CLI? Cause these are what those are really

**Comment by espensgr** [comment]
maybe this would be solved with a [project spec](#263)?
