### ISSUE TITLE
Error logging in to CLI. Please try again

### ISSUE THREAD

**Issue by lassv** [railwayapp/cli#212]
Hello there. A month ago I tried to log in to Railway CLI but It doesn't work at all.

Error: <pre>Error logging in to CLI. Please try again</pre>

And it throws the same error, still if i try the <pre>npx railway login</pre>.

<img width="825" alt="Screenshot 2022-03-29 at 09 00 01" src="https://user-images.githubusercontent.com/77295879/160552300-4c4b9b93-14ff-4dc3-8681-d6872ec8c909.png">

**Cheers**
_lasse_

**Comment by GrimZZZ-404** [comment]
Add `--browserless` flag

**Comment by FarazPatankar** [comment]
Closing as it appears to have been resolved!
