### ISSUE TITLE
npm i -g @railway/cli is broken

### ISSUE THREAD

**Issue by jmcelreavey** [railwayapp/cli#219]
Current workaround:
Install previous version: 
`npm i -g @railway/cli@1.5.0`

Error:
npm ERR! path /home/johnny/.nvm/versions/node/v16.15.0/lib/node_modules/@railway/cli
npm ERR! command failed
npm ERR! command sh -c node ./npm-install/postinstall.js
npm ERR! Error: Failed fetching the binary: Not Found
npm ERR!     at install (file:///home/johnny/.nvm/versions/node/v16.15.0/lib/node_modules/@railway/cli/npm-install/postinstall.js:29:11)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by coffee-cup** [comment]
This has been fixed with the latest release https://github.com/railwayapp/cli/releases/tag/v1.5.2
