### ISSUE TITLE
Railway login doesn't work

### ISSUE THREAD

**Issue by scratcher-402** [railwayapp/cli#221]
`railway login` shows this:
`Post "https://backboard.railway.app/graphql": dial tcp: lookup backboard.railway.app on [::1]:53: read udp [::1]:58035->[::1]:53: read: connection refused`
All other railway cli commands don't work and are asked to run railway login.

**Comment by wyzlle** [comment]
Which operating system are you using CLI on?

**Comment by scratcher-402** [comment]
> Which operating system are you using CLI on?

Android (termux)

**Comment by wyzlle** [comment]
CLI isn't compatible with android(termux) yet. You can build it locally for now.

```bash
pkg install golang git
git clone https://github.com/railwayapp/cli.git
cd cli/
go build -o bin/railway
rm $PREFIX/bin/railway
cp bin/railway $PREFIX/bin
```

**Comment by scratcher-402** [comment]
> CLI isn't compatible with android(termux) yet. You can build it locally for now.
> 
> ```shell
> pkg install golang git
> git clone https://github.com/railwayapp/cli.git
> cd cli/
> go build -o bin/railway
> rm $PREFIX/bin/railway
> cp bin/railway $PREFIX/bin
> ```

It is because I used Railway cli and deployed my projects from termux a few months ago (I installed it via bash script). But now it doesn't work

**Comment by JakeCooper** [comment]
Closing due to merged Android support. Should work now
