### ISSUE TITLE
Auto create service on up

### ISSUE THREAD

**Issue by JakeCooper** [railwayapp/cli#232]
If there's no service found in the project when doing up, we should bootstrap one and up to it

**Comment by coffee-cup** [comment]
I’m pretty sure railway does this automatically

**Comment by wyzlle** [comment]
> I’m pretty sure railway does this automatically

No, Request fails with service not found error.
Error Logs - `🚃 Laying tracks in the clouds... {"message":"Service not found","reqId":"626edcb0-dfa7-431a-ac49-b4e2b23eb01f"}`

**Comment by coffee-cup** [comment]
Oh this is a bug on Railways side then. It used to auto create the service. Will keep this open for now but now cli specific code should need to be written.

**Comment by JakeCooper** [comment]
> I’m pretty sure railway does this automatically

We technically used to handle it but that only worked because we used to fall back to the hidden "deployment" service

Now since we've made serviceId required it doesn't work
