### ISSUE TITLE
provide better error messages when trying to login using safari

### ISSUE THREAD

**Issue by anuaimi** [railwayapp/cli#233]
when I tried `railway login` it opened up a page in safari with the message "error logging into CLI.  Please try again".  It should be more clear that Safari is not supported right now and the user should try another browser.

I had this issue yesterday and reported it in Discord.  I was told that Safari is not support. It would be helpful to have the CLI/webpage be more clear as to way there is an error and how the user can resolve it.

**Comment by coffee-cup** [comment]
Hi @anuaimi,

Safari is supported but requires the `--browserless` flag. Did that work for you?

e.g.

```
railway login --browserless
```

I agree that the error message in the browser should be better though. I do believe we suggest trying the browserless login if regular login fails.

**Comment by anuaimi** [comment]
It did but the issue is I had to find out about the flag on discord. The webpage should have a more clear message about this. This github issue is about improving the ux

**Comment by anuaimi** [comment]
The only thing the webpage showed was that there was an error. No details on why or what else to try.

**Comment by GetPsyched** [comment]
I'm not sure if it did back then, but the CLI does prompt you to try `--browserless` when I checked just now. Also, that prompt being in the CLI is fine since that's where the origin of the login request lies.
