### ISSUE TITLE
Verifying a New Account with Payment Method

### ISSUE THREAD

**Issue by CalTricks** [railwayapp/cli#240]
I have never used Railway before and seemingly cannot.

I see that you've recently introduced requiring a Payment Method for verification, I think that's completely fair. I've created an account, setup a GitHub, and added my Credit Card - that's showing as verified.

However, I simply can't use Railway:
I can't create a new project from a GitHub repo, because I'm "not verified"
I get an error logging into CLI even with --browserless
When trying to create a Token, it says I can't because I'm "not verified"

These problems maybe unrelated to verification, because I have no experience with this, but it seems like that's the case as I'm prompted to visit [https://railway.app/verify](https://railway.app/verify) where I see the following: [https://ibb.co/2czvvNM](https://ibb.co/2czvvNM)

Is the verification "OR" as suggested? If so, is this an error?

How does someone new to programming and wanting to get started with Railway do so? I understand the need for a card and think that's completely reasonable, but I've done so and yet I seemingly can't use the service.

**Comment by ndneighbor** [comment]
Oh dear, forgive me as I was the engineer who implemented this system. 

We ran into an issue with crypto miners attaching a card and then ripping some weird workloads. We then added some safeguards of which that caught some folks. We have since rolled back those changes. We have since fixed that error in the system and your account.

**Comment by kwmc-lucas** [comment]
That's alright, I don't mind the policy either because people shouldn't be using your service for that!

It was just a little unclear on what I had to do to become verified.

Thanks for sorting my account out, looking forward to learning how to use this thing...

**Comment by CalTricks** [comment]
That's alright, I don't mind the policy either because people shouldn't be using your service for that!

It was just a little unclear on what I had to do to become verified.

Thanks for sorting my account out, looking forward to learning how to use this thing...
