### ISSUE TITLE
Deploy a Docker image

### ISSUE THREAD

**Issue by JuanM04** [railwayapp/cli#254]
It would be nice to have a way to deploy a single Docker image as a service.

Something like `railway up --image edgedb/edgedb`

**Comment by JakeCooper** [comment]
It’ll require config and other things

An image is only part of the equation. Templates, ideally, should encapsulate all of this

**Comment by JuanM04** [comment]
> There are almost zero images that’ll work out of the box.

That's right, but having this command would help a lot when there are no templates. Also, it would make it very easy to update an image

**Comment by espensgr** [comment]
maybe this would be solved with a [project spec](#263)?
