### ISSUE TITLE
unable to railway up with Token

### ISSUE THREAD

**Issue by wrench1815** [railwayapp/cli#255]
## Problem
Unable to use `railway up` with `RAILWAY_TOKEN`. Other commands like status, variables, shell and run all are working.

Also railway cli works fine when logged in using `railway login`

## Reproduction
```
RAILWAY_TOKEN=<token> railway up
```

## Error
```
lstat : no such file or directory
```

## Expected
able to deploy the application

**Comment by JakeCooper** [comment]
What operating system?

**Comment by wrench1815** [comment]
Manjaro Linux

also same error comes up when using ci like Github Actions

**Comment by coffee-cup** [comment]
I've found the issue. PR incoming!
