### ISSUE TITLE
Build doesn't work when an empty service is created and source files are uploaded using `railway up`

### ISSUE THREAD

**Issue by anilbhanushali** [railwayapp/cli#257]
When an empty service is created under a project via dashboard, and source files are uploaded using 'railway up',  build does not work.

Here's the sample repo for [expressjs](https://github.com/anilbhanushali/expressjs) app which i used to tryout

however If I create a project connected to Github via dashboard, it works fine.

and if at any point I upload files using 'railway up' it stops working again and there is an error screenshot and with no information other than docker build in build logs.

<img width="832" alt="image" src="https://user-images.githubusercontent.com/7549804/183149114-75bdf285-1e0a-4265-9bd9-43b860d9b6b1.png">

**Comment by coffee-cup** [comment]
Please create an issue on the [Railway Discord server](https://discord.gg/railway) in the #project-help channel as this error is not related to the Railway CLI.
