### ISSUE TITLE
Locally running `railway up` ignores `.gitignore`

### ISSUE THREAD

**Issue by ChristianIvicevic** [railwayapp/cli#259]
I just noticed weird behavior while experimenting wherein running `railway up` manually in my directory has resulted in deployments that do not match the source code at that time. For debugging purposes I ran a script to list all files that have been uploaded and noticed that not a single file in the `.gitignore` has been ignored resulting in outdated artifacts being uploaded and especially local `.env` files interfering with the build process.

Please let me know whether you need any information about system, repo structure etc. in order to reproduce this issue on your end.

**Comment by ravivyas84** [comment]
>running `railway up` manually in my directory has resulted in deployments that do not match the source code at that time 

I had the same issues yesterday... I had to delete the build and dist folders before running `railway up` again.
