### ISSUE TITLE
railway up command throws error regarding file IO

### ISSUE THREAD

**Issue by usavas** [railwayapp/cli#261]
After I link my project and I am able to access and run the project on localhost, I run the command railway up, it gives me seemingly unrelated errors such as

> "lstat /Library/Application Support/Adobe: no such file or directory" 

and immediately stops running.

First I got a similar error for google drive folders on my Mac and deleted them to avoid the error. And then again I got this one. What does ```railway up``` command have to do with unrelated files and folders on my Mac. There is not anything wrong with my project setup, it is actually running locally and on the railway server.

Please show me a way of getting around this error.
Thanks

**Comment by coffee-cup** [comment]
What version of the CLI do use see this issue with?

**Comment by nilzzzzzz** [comment]
Same issue here. For example: 
❯ railway up
🚨 open /Users/Nils/.Trash: operation not permitted

railway --version
railway version 2.1.0

**Comment by Milo123459** [comment]
can you try again with cli v3?
