### ISSUE TITLE
Error Installing CLI

### ISSUE THREAD

**Issue by rtk-rnjn** [railwayapp/cli#268]
I am new to Railway App, and don't really know how to proceed! I tried installing CLI from `curl` as documented. And getting this error

```bash
C:\Users\Ranjan>curl -fsSL https://railway.app/install.sh | sh
Error: CYGWIN_NT-6.1 os type is not supported
Please create an issue so we can add support. https://github.com/railwayapp/cli/issues/new
```
```bash
C:\Users\Ranjan>uname -a
CYGWIN_NT-6.1 Ritik-Ranjan-PC 3.2.0(0.340/5/3) 2021-03-29 08:42 x86_64 Cygwin
```

**Comment by nebulatgs** [comment]
Curl install is not supported on Windows

**Comment by nebulatgs** [comment]
Try using NPM/Yarn or Scoop instead

**Comment by rtk-rnjn** [comment]
@nebulatgs Thanks for the quick reply, `NPM` does work. But I want to ask if there is any future idea for supporting the `curl` install on Windows?

**Comment by nebulatgs** [comment]
> @nebulatgs Thanks for the quick reply, `NPM` does work. But I want to ask if there is any future idea for supporting the `curl` install on Windows?

`curl` is not a default command on Windows, so we can't really support it. Cygwin `curl` is uncommon, so we probably won't support it.
