### ISSUE TITLE
Can't connect to Railway.

### ISSUE THREAD

**Issue by Sylph1de** [railwayapp/cli#276]
I've tried with GitHub AND Email. When I try with GH, site will always respond with the image below. And when I use Email, I'll get an error: 'Failed to fetch'.
I have a good internet connection, I have Firewall disabled, and I don't use a Proxy.
![image](https://user-images.githubusercontent.com/88037480/191053389-0138bb77-3032-4d2b-bb6f-ee412240d82b.png)

**Comment by GetPsyched** [comment]
Hey! Is this still an issue? Check if you have anything that you're forwarding to `localhost` inside your project

**Comment by Sylph1de** [comment]
Fixed by itself. Still don't know what the issue was.
