### ISSUE TITLE
Bash installer: Permission denied

### ISSUE THREAD

**Issue by abe-101** [railwayapp/cli#277]
When I run the bash installer on my fedora machine I get this error:

```
mv: cannot create regular file '/usr/local/bin/railway': Permission denied
```

running the cmd with `sudo` doesn't help

my guess is this is the problomatic line 
https://github.com/railwayapp/cli/blob/22b8aafc33cf713a1c0f84c5408112f6c14fff4d/install.sh#L150

**Comment by TatisLois** [comment]
Not sure if this will help but ran into a similar issue Permission denied and this resolved it 
`sudo chown -R $(whoami) /usr/local/bin`

from -> https://github.com/railwayapp/cli/issues/104
