### ISSUE TITLE
docs shows environment flag, cli does not

### ISSUE THREAD

**Issue by 3commascapital** [railwayapp/cli#279]
the `-e` or `--environment` flag is claimed to exist [in the docs](https://docs.railway.app/reference/cli-api#flags-1) however, the cli does not seem to support it. i would prefer that the cli support it if possible. current workaround is `railway environment x > /dev/null && ...`

**Comment by gschier** [comment]
Hey there. I just tried an example project and confirmed that the `--environment` flag does indeed work on version `2.0.13`.

Note that this is only supported for the `up` command and should be specified as `railway up --environment development`. You may need to add quotes if your environment contains special characters like `railway up --environment 'My Environment'`.

I'm going to close this for now but feel free to reply if you're still having issues 👋🏻
