### ISSUE TITLE
strange failure trying to run `railway up`

### ISSUE THREAD

**Issue by sgrund14** [railwayapp/cli#280]
running on railway 2.0.7

when I try to run `railway up` for a linked project, I get this error

```
🚞 Laying tracks in the clouds...
🚨 open /Users/samgrund/.docker/run/docker-cli-api.sock: operation not supported on socket
```

any ideas what's wrong?

**Comment by Mr-Destructive** [comment]
Maybe try the same command with `sudo` or higher permission as the `Run as Administrator` command. 
```
sudo railway up
```

**Comment by MH15** [comment]
Still an issue on my end.

**Comment by bradpurchase** [comment]
Same here. This is a fresh Homebrew install on macOS:

```
»  railway up
🚨 open /Users/bradpurchase/.Trash: operation not permitted
```

**Comment by bengribbinpl** [comment]
Same issue my end too.

.Trash: operation not permitted
