### ISSUE TITLE
issue when using `railway up`

### ISSUE THREAD

**Issue by subtosharki** [railwayapp/cli#283]
i tried to start one of my projects using `railway up` and it goes for a bit but then gives me this error:

```read /home/cameron/.local/share/flatpak/appstream/flathub/x86_64/48170d83669ae813c1ec17004bac11a446dc837993dd4e1e1525f2ea96f693ed/icons: is a directory```

its my first time running the command, downloaded it through the npm install

ive tried running this with sudo and get the same issue

**Comment by subtosharki** [comment]
just uninstalled through npm and installed with sh and still doing the same thing

**Comment by nebulatgs** [comment]
join the discord https://discord.gg/railway
