### ISSUE TITLE
Connecting to django postgres database service using cli

### ISSUE THREAD

**Issue by gerrydevine** [railwayapp/cli#284]
Hi. How do I connect to my Django-app linked postgres database? I have a local django development app set up with connections to a local dev postgres database. I have now hooked that up to a railway app (with railway postgres service) for production and want to migrate the database there as well as add a superuser. I can connect to the app using railway cli and can see my railway and postgres variables listed. But when I try and do anything, e.g. railway run python manage.py makemigrations it only tries and runs this against my local dev database. How do I therefore get my production database up and running?

**Comment by GetPsyched** [comment]
By production database, do you mean the database service setup inside of a Railway project?

**Comment by GetPsyched** [comment]
Did you check your connection URL for your PostgreSQL service on Railway?
