### ISSUE TITLE
Request Entity Too Large

### ISSUE THREAD

**Issue by GuilhermeAmado** [railwayapp/cli#288]
Request Entity Too Large
<img width="542" alt="Captura de Tela 2022-11-02 às 16 20 15" src="https://user-images.githubusercontent.com/49161599/199581867-f87af041-0905-4071-b2e6-5bbd4b4fed9e.png">

I'm having this error when I try to use 'railway up'

Any solutions?

**Comment by GuilhermeAmado** [comment]
The project in question has about 40mb btw

**Comment by Eejit43** [comment]
Seems to be an issue with railway (not the cli)– it doesn't deploy from larger repos. Not sure why it is happening for you though–

**Comment by JabalnurIT** [comment]
have you found the solution?

**Comment by Milo123459** [comment]
yeah railway up cannot transfer that much, thus it gets rejected. please use a github repo
