### ISSUE TITLE
read: <directory> is a directory

### ISSUE THREAD

**Issue by JakeCooper** [railwayapp/cli#295]
Issue seems to occur when trying to deploy [Discourse](https://github.com/discourse/discourse) with railway up

<img width="794" alt="CleanShot 2023-01-10 at 12 58 06@2x" src="https://user-images.githubusercontent.com/5499880/211661129-506267a8-d8a8-4640-a5f0-81b914c0fdfc.png">

**Comment by gschier** [comment]
Oops, forgot to close this one in #296
