### ISSUE TITLE
Redeploy command

### ISSUE THREAD

**Issue by Eejit43** [railwayapp/cli#298]
With the addition of the Redeploy button a few months ago, it would be handy to have this same functionality as a cli command. Something like "railway redeploy latest" would be especially useful as there isn't a way to stop and restart a project using the CLI as of writing this.

Note: moved from [Canny post](https://railway.canny.io/feature-requests/p/redeploy-cli-command).

**Comment by GrantBirki** [comment]
I second this motion. It would be fantastic to have a `railway restart` command. Calling `railway up` and doing a fresh deploy "works" but perhaps it would be better to have something in the CLI that more closely aligns with what we see in the web UI

<img width="300" alt="Screenshot 2023-08-05 at 10 37 48 PM" src="https://github.com/railwayapp/cli/assets/23362539/ea82220f-30d5-4f40-bdd9-694bc08c6e82">

@coffee-cup Thoughts?
