### ISSUE TITLE
`railway link` should take second argument for `environment`

### ISSUE THREAD

**Issue by charkour** [railwayapp/cli#303]
The ideal syntax for `railway link` would be `railway link <project-id> <environment>`.

I'm not familiar enough with Go to make that change. 

Thank you

**Comment by ndneighbor** [comment]
Hey @charkour - this should be fixed in https://github.com/railwayapp/cliv3

We should expect much more CI native flags that help you be more explicit.

**Comment by charkour** [comment]
Thanks, I didn't realize there were different repos for the CLI. A little confusing.

Thank you for the swift reply! I appreciate the product you're making :)
