### ISSUE TITLE
[Feature Request] install.sh for a specific version of railway

### ISSUE THREAD

**Issue by alexng353** [railwayapp/cli#314]
Would be nice to be able to select specific version when installing using install.sh

`curl -fsSL railway.sh | sudo bash s -- -v 3.0.3` for example

**Comment by coffee-cup** [comment]
You can install a specific version of the CLI by setting the `RAILWAY_VERSION` environment variable.

For example
```
RAILWAY_VERSION=3.0.22 bash <(curl -fsSL cli.new)
```
