### ISSUE TITLE
CLI not reading/showing shared environment variables

### ISSUE THREAD

**Issue by Phifo** [railwayapp/cli#321]
The `railway run` command fail to execute because is not reading my shared enrivonment variables and the `railway variables` command shows all my shared environment empty. Non-shared environment variables are working fine.

**Comment by nebulatgs** [comment]
What version of the CLI are you on?

I believe this was patched on the latest version, could you give it a try now and let me know?

**Comment by coffee-cup** [comment]
This has since been fixed
