### ISSUE TITLE
BUG - New V3 doesn't support service parameter inside up command. 

### ISSUE THREAD

**Issue by uragecz** [railwayapp/cli#331]
Hey, with new major version my gitlab CI starts crashing from yesterday.. I was able to partly migrate to v3, but i am stuck with `railway up` command. In v2 there was property to specify which service i wanna turn on  `--service`. In new v3 there is not such a option and i can't find anywhere how to specify that.
Is there any alternative for this option or you just forgot to implement this key feature in new version ?

**Comment by taig** [comment]
`--environment` and `--service` flags seem to be broken. I had to pin my version to 2.1.0 to get my CD pipelines working again ):

**Comment by uragecz** [comment]
How did you specify version ? I tried -   ` curl -fsSL https://raw.githubusercontent.com/railwayapp/cli/v2.1.0/install.sh | sh` but this script inside is trying to install still latest version - 3xx.... :(

**Comment by taig** [comment]
I'm using it in GitHub Actions via `npm install railway/cli@2.1.0`

**Comment by coffee-cup** [comment]
The service flag is now available in the latest version. The environment flag will be added soon (PR is open)
