### ISSUE TITLE
Request: Branch protections and required CI checks

### ISSUE THREAD

**Issue by GrantBirki** [railwayapp/cli#337]
# Branch Protections and Required CI checks

This issue requests branch protections and required CI checks to be enabled for the [`railwayapp/cli`](https://github.com/railwayapp/cli) repository.

It might be due to the fact that I am not a member of this repository / org but it looks like there are no required CI checks on this repo. I can see that there _are_ CI checks but none of them are required. This may not be available to this organization depending on your plan, but if you are able to add [branch protection rules](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule), I would highly suggest doing so.

I would also suggest requiring a member of the organization to approve CI runs from all outside contributors.

**Comment by nebulatgs** [comment]
These are already enabled

**Comment by GrantBirki** [comment]
Wonderful! It was probably just due to my permissions that I could not see if they were `required`
