### ISSUE TITLE
Error: unrecognized subcommand 'connect'

### ISSUE THREAD

**Issue by Ruslanmsv** [railwayapp/cli#343]
Trying to connect to database via `railway connect postgresql` as proposed in Connect tab of UI or documentation and getting error:
```
❯ railway connect
error: unrecognized subcommand 'connect'

Usage: railway [OPTIONS] <COMMAND>

For more information, try '--help'.
```

I've installed railway CLI on macOS via Homebrew.
App version:
```
railway --version
railwayapp 3.0.1
```

**Comment by nawok** [comment]
Not implemented. Use `railway --help` and it will display everything what is supported. The `--help` is autogenerated based on existing program code.

**Comment by popovbm** [comment]
I had the same problem. Need to update railway version

> FWIMC: The Railway UI and documentation should be probably updated accordingly
> 
> <img alt="image" width="300" src="https://user-images.githubusercontent.com/2587952/223716544-7c746f82-811c-45f2-b28c-d7d1f1a10774.png">
> 
> https://docs.railway.app/develop/cli

I had the same problem. Need to update railway version
