### ISSUE TITLE
NPM install still fails in Windows 11

### ISSUE THREAD

**Issue by moinulmoin** [railwayapp/cli#348]
Windows - 11
Node.js - v18.13.0
Terminal - Git Bash

![image](https://user-images.githubusercontent.com/63459189/224321041-ddf23264-8982-4828-8f31-151816da11c7.png)

**Comment by maddsua** [comment]
I'm also experiencing this issue, it seems that the tar.gz file does not contain a tarball inside, and it's just a gz archive, so yeah, npm will fail to extract it.

By the way, I like the fact that CLI itself is not a huge mess of node packages.
upd: oh, it's in Rust. wow
