### ISSUE TITLE
CLI tool does not exit after operation is complete

### ISSUE THREAD

**Issue by maddsua** [railwayapp/cli#383]
After running `railway up`, the CLI tool does not exit and just stays like this:

![image](https://user-images.githubusercontent.com/102395937/224575260-5514af0d-7e43-484a-9ff1-0ba07e360b74.png)

Is this a bug or a feature? I don't see any way to further interact with the tool but to exit with Ctrl+C.

OS: windows 10

**Comment by nebulatgs** [comment]
You can use the `--detach` or `-d` flag to detach from streaming logs.

**Comment by maddsua** [comment]
> You can use the `--detach` or `-d` flag to detach from streaming logs.

To me, the default behavior seems unusual, but okaaay, thanx
