### ISSUE TITLE
CTRL + C drops users out of non-railway shells

### ISSUE THREAD

**Issue by JakeCooper** [railwayapp/cli#384]
Flow: 

* A user starts a `rails c` console session
* A user runs `railway run`
* A user hits CTRL + C

Expected Behavior:
* The user is dropped out of the `railway run` command but NOT the surrounding rails console

Observed Behavior:
* The user is dropped out of the `railway run` command AND the surrounding rails console

Suggested Resolution:
* Capture the CTRL + C and do not propagate it upwards

Workaround:
* Use `railway shell` and then use `rails c`

**Comment by honzasterba** [comment]
not sure about the expected behaviour, I would describe it more like:
CTRL+C is passed to the running process invoked by `railway run X`, the process handles it as it sees fit

In case of `rails c` it just resets the current REPL command, does not terminate the process
