### ISSUE TITLE
Running `railway environment` multiple times causes invalid config.json

### ISSUE THREAD

**Issue by half0wl** [railwayapp/cli#391]
On `railwayapp 3.0.12`, I get a corrupted `~/.railway/config.json` file after switching environments multiple times.

This is how to reproduce:

1. Start with a fresh state (no `config.json`):

```sh
$ rm -f ~/.railway/config.json
$ cat ~/.railway/config.json
cat: /Users/ray/.railway/config.json: No such file or directory
```

2. Login and link current directory to project:
```sh
$ railway login
$ railway link
> Select a project redacted
> Select an environment test

# config.json is fine at this stage
$ cat ~/.railway/config.json
{
  "projects": {
    ...
  },
  "user": {
    "token": "redacted"
  }
}
```

3. Switch environment:
```sh
$ railway environment
> Select an environment production

# config.json is still ok
$ cat ~/.railway/config.json
{
  "projects": {
    ...
  },
  "user": {
    "token": "redacted"
  }
}
```

4. Switch environment again:
```sh
$ railway environment
> Select an environment test

# Now config.json is broken:
$ cat ~/.railway/config.json
{
  "projects": {
    ...
  },
  "user": {
    "token": "redacted"
  }
}
  }         <-- Shouldn't be here
}           <-- Shouldn't be here
```

**Comment by half0wl** [comment]
Closing, fixed by #394 and released in version [3.0.16](https://github.com/railwayapp/cli/commit/d4c4cae9fecfbe9f7bc5bd00d16877fef7e69490)

**Comment by Jbarget** [comment]
@half0wl it seems like the version on npm is still `3.0.13`

**Comment by half0wl** [comment]
> @half0wl it seems like the version on npm is still `3.0.13`

Yeah, unfortunately we're having some issues with our npm publishing process :-(

I recommend installing via other methods for now - https://docs.railway.app/develop/cli#install
