### ISSUE TITLE
Is `v3.0.16` the latest release?

### ISSUE THREAD

**Issue by ZhongRuoyu** [railwayapp/cli#395]
Hi! [Homebrew](https://github.com/Homebrew/brew) maintainer here. I noticed that `v3.0.16` was tagged, but is not yet marked as latest on the repo's [releases page](https://github.com/railwayapp/cli/releases). Instead, `v3.0.9`, committed 2 weeks ago, was marked as latest 3 hours ago. I'm filing this issue to confirm if that was intended. Thanks!

**Comment by ndneighbor** [comment]
Hey there @ZhongRuoyu! First off thanks for noticing, we are busy porting over our CI for this version of the CLI. We broke GoReleaser :'( 

I am going to see if I can move the `latest` tag to `3.0.16` - thanks for flagging!

**Comment by ndneighbor** [comment]
(Going to tag in @nebulatgs and @gschier who are maintaining the CLI)

**Comment by ZhongRuoyu** [comment]
Hi @ndneighbor, thanks for the quick response! Hopefully it can be fixed soon. Meanwhile, let me proceed to ship `v3.0.16`.

**Comment by ndneighbor** [comment]
I know one of the most annoying things about maintenance is the reply time :') 

Do you have good examples of Rust CLI's who have good automated brew release pipelines? Our main goal here is to make it so that `brew install railway` is restored to proper and correct versions without human intervention.

**Comment by ZhongRuoyu** [comment]
> Do you have good examples of Rust CLI's who have good automated brew release pipelines?

I think you may want to have a look at https://github.com/jdxcode/rtx 's workflow [here](https://github.com/jdxcode/rtx/blob/main/.github/workflows/rtx.yml). They also publish new releases quite frequently. I can often see their bot automatically publish new releases on GitHub and send PRs to Homebrew/core.

**Comment by gschier** [comment]
Oh yep, my bad. I had accidentally pushed an old tag that created a new release, which is why `v3.0.9` was showing for you.
