### ISSUE TITLE
railway logs -d commend gives TLS error

### ISSUE THREAD

**Issue by SunGunes** [railwayapp/cli#396]
I am trying to get the production logs from my computer but im getting TLS error?
railway logs -d

Error: TLS error: webpki error: UnsupportedCriticalExtension

Caused by:
    0: webpki error: UnsupportedCriticalExtension
    1: UnsupportedCriticalExtension
    
    Is this because of me or general problem ? 
    Thank you!
    Have a nice day!

**Comment by coffee-cup** [comment]
I believe this is an issue with your network. I am unable to reproduce and it doesn't seem to be an issue that others are having. Closing for now

**Comment by AlexJBlair** [comment]
I have run into this issue as well. I am not really doing anything special as far as network security and I simply ran the command `railway up`.
