### ISSUE TITLE
Environment flag for `up` command

### ISSUE THREAD

**Issue by 0xMukesh** [railwayapp/cli#399]
The v2 CLI had a flag for specifying the environment where it would be deployed. It made the development CI/CD process much easier. 
The v3 CLI doesn't have a flag for specifying the environment (yet). If you want to deploy to a non-production environment (`development`), you'll need to run the `link` command along with the environment to which it should be deployed.

```bash
$ railway link <project-id> --environment development && railway up
```

**Comment by uragecz** [comment]
Same problem with --service flag...

**Comment by coffee-cup** [comment]
Fixed in https://github.com/railwayapp/cli/pull/351
