### ISSUE TITLE
Error: Cross-device link (os error 18)

### ISSUE THREAD

**Issue by gazhay** [railwayapp/cli#402]
Ubuntu 22.04.02 LTS, railway installed via ```curl -fsSL https://railway.app/install.sh | sh```

I have different physical disks for "/" and "/home"

I cannot login either with ```railway login``` or ```railway login --browserless```

Both fail with 

```Error: Cross-device link (os error 18)```

I attempted to copy the railway binary to the same physical disk as the ~/.railway directory  but this did not work.
I copied the binary back to the root file system and symlinked ~/.railway to the root file system physical disk, this too did not work.

It would seem the the linux mv tool works around this same problem. A failed rename() call hitting error 18 it falls back to a copy.

**Comment by half0wl** [comment]
@gazhay this should be fixed in #403 and released in the latest version. Can you confirm if this still happens? Thanks!
