### ISSUE TITLE
at the very first step, railway link <code> returns error

### ISSUE THREAD

**Issue by gitgetgotgotten** [railwayapp/cli#405]
I just created an empty project and run the command `railway link <code>`, and it returned the error:

> Error: error decoding response body: expected value at line 2 column 1
> 
> Caused by:
>     expected value at line 2 column 1

It is not just about `railway link`, but `railway init` is like that too.

I'm on Windows 10.

**Comment by coffee-cup** [comment]
Can you check again with the latest version. This should now be fixed

**Comment by gitgetgotgotten** [comment]
Not yet!
Now it returns this:

> Failed to fetch: error sending request for url (https://backboard.railway.app/graphql/v2): connection error: unexpected end of file
> 
> Caused by:
>     0: error sending request for url (https://backboard.railway.app/graphql/v2): connection error: unexpected end of file
>     1: connection error: unexpected end of file
>     2: unexpected end of file

My firewall is off.
It shows 3.2.0 when I run the `railway --version`.
I thought maybe my country has banned the access to the URL that is in the error, so I used a VPN but that didn't work too.
