### ISSUE TITLE
Checking for banned dependencies is incorrect

### ISSUE THREAD

**Issue by RokasKasnauskas** [railwayapp/cli#408]
Checking for banned dependencies is incorrect.
As I understand currently it searches for banned dependencies as keywords in package.json. It should look what is under dependencies instead, because project name, other dependencies or scripts could have banned dependency name inside it. 

For example problem that I got was it found banned dependency 'eunha' inside my script command
 vitest --dangerouslyIgnor**eUnha**ndledErrors

**Comment by coffee-cup** [comment]
This is indeed a valid concern, but is not an issue with the CLI specifically. Can you please create a bug/feature request in Canny instead https://railway.canny.io/feature-requests
