### ISSUE TITLE
Can't install railway cli

### ISSUE THREAD

**Issue by ghiathalabbase** [railwayapp/cli#428]
I am tring to install railway cli using npm but I still get this error: 
"npm ERR! code 1
npm ERR! path C:\Users\TECH-GATE\AppData\Roaming\npm\node_modules\@railway\cli
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node ./npm-install/postinstall.js
npm ERR! https://github.com/railwayapp/cli/releases/download/v3.3.1/railway-v3.3.1-i686-pc-windows-gnu.tar.gz
npm ERR! Error: Failed fetching the binary: Not Found
npm ERR!     at install (file:///C:/Users/TECH-GATE/AppData/Roaming/npm/node_modules/@railway/cli/npm-install/postinstall.js:30:9)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

npm ERR! A complete log of this run can be found in: C:\Users\TECH-GATE\AppData\Local\npm-cache\_logs\2023-05-26T21_26_41_241Z-debug-0.log
"

**Comment by coffee-cup** [comment]
What OS are you using?

**Comment by ghiathalabbase** [comment]
> What OS are you using? I'm assuming Windows, what version?

Windows 10

**Comment by cristianosch** [comment]
I am having the same issue, windows 11

**Comment by Gridonyx** [comment]
I'd be curious to see that the system architecture is... The value of `triples.raw` from postinstall.js on your system, `i686-pc-windows-gnu`, is a value that isn't supported within the current list of CLI releases which is why you're getting the `Error: Failed fetching the binary: Not Found` message.

**Comment by maddsua** [comment]
Guys! There's literally no such target as `i686-pc-windows-gnu`. It should be an easy fix

**Comment by maddsua** [comment]
How about close this one? It's been fixed in #389
