### ISSUE TITLE
Errors about streaming logs when deploying from command line

### ISSUE THREAD

**Issue by joelanman** [railwayapp/cli#431]
When I deploy from the command line using `railway up`, it deploys fine but I get two errors:

```
railway up
  Indexed                                                                                       
  Compressed [====================] 100%                                                        
  Uploaded                                                                                        Build Logs: [redacted]
Failed to stream build logs: TLS error: webpki error: MissingOrMalformedExtensions
Failed to stream deploy logs: TLS error: webpki error: MissingOrMalformedExtensions
```

railwayapp 3.3.1
macOS 13.4
no vpn or proxy

**Comment by zuchka** [comment]
hi @joelanman,


are you still encountering this error? sorry for the delay

**Comment by joelanman** [comment]
I don't think I've seen it recently, closing this and will reopen if it happens again

**Comment by MokuaEnock** [comment]
Hello Still facing this issue 

Failed to stream build logs: TLS error: webpki error: MissingOrMalformedExtensions
Failed to stream deploy logs: TLS error: webpki error: MissingOrMalformedExtensions
