### ISSUE TITLE
Accessing project's environment directly [CRONJOBS]

### ISSUE THREAD

**Issue by Emad-Eldin-G** [railwayapp/cli#442]
Can we use the current version of the CLI to access the project's environment on the cloud?

Basically, I need to set up cronjobs for explicit file paths in my project, the web interface only allows a single cronjob for the whole project.

**Comment by Emad-Eldin-G** [comment]
I am part of the beta program by the way...

**Comment by brody192** [comment]
railway doesn't provide any way to ssh into the container, for more fine grained control over cron you may want to look into an in code cron or scheduler package.

for future questions please ask in discord, this it github issues
