### ISSUE TITLE
Gitlab CI error:  sending request for url: backboard.railway-develop.app failure

### ISSUE THREAD

**Issue by knewman23** [railwayapp/cli#447]
I am running the install setup in Gitlab CI and it seems like the script is pointing to an older version of this endpoint:

`https://backboard.railway-develop.app/graphql/v2` when I removed the `-develop` the link seems to work but I can't do this in a CI pipeline?

`$ RAILWAY_TOKEN=$RAILWAY_TOKEN railway environment $RAILWAY_ENV`

```
Failed to fetch: error sending request for url (https://backboard.railway-develop.app/graphql/v2): error trying to connect: tcp connect error: Connection refused (os error 111)
Caused by:
    0: error sending request for url (https://backboard.railway-develop.app/graphql/v2): error trying to connect: tcp connect error: Connection refused (os error 111)
    1: error trying to connect: tcp connect error: Connection refused (os error 111)
    2: tcp connect error: Connection refused (os error 111)
    3: Connection refused (os error 111)
```

**Comment by half0wl** [comment]
> when I removed the `-develop` the link seems to work but I can't do this in a CI pipeline?

Can you elaborate on why you're using this?

You should definitely remove the `-develop` flag; it's not a flag for "this is a CI environment," it's for setting the Railway API environment which you _shouldn't_ use in your project

**Comment by half0wl** [comment]
> I am running the install setup in Gitlab CI and it seems like the script is pointing to an older version of this endpoint:
> 
> `https://backboard.railway-develop.app/graphql/v2` when I removed the `-develop` the link seems to work but I can't do this in a CI pipeline?
> 
> `$ RAILWAY_TOKEN=$RAILWAY_TOKEN railway environment $RAILWAY_ENV`
> 
> ```
> Failed to fetch: error sending request for url (https://backboard.railway-develop.app/graphql/v2): error trying to connect: tcp connect error: Connection refused (os error 111)
> Caused by:
>     0: error sending request for url (https://backboard.railway-develop.app/graphql/v2): error trying to connect: tcp connect error: Connection refused (os error 111)
>     1: error trying to connect: tcp connect error: Connection refused (os error 111)
>     2: tcp connect error: Connection refused (os error 111)
>     3: Connection refused (os error 111)
> ```


(I deleted a previously inaccurate comment here to avoid confusion, ignore if you received a notif about it)

Can you do an `echo $RAILWAY_ENV` there and paste the output here?

**Comment by knewman23** [comment]
Turns out I was setting RAILWAY_ENV to dev, removing that worked!
