### ISSUE TITLE
Can't not display Image with Nextjs version : 13.5.3  

### ISSUE THREAD

**Issue by Tyronwilliam** [railwayapp/cli#450]
Hi there  !

### Description

When deploy to production a Nextjs App, when fetch Image tag display this error 

![image](https://github.com/railwayapp/cli/assets/70233964/bcab737e-30cf-441f-bfc4-981326834ebd)

### Package.json

![image](https://github.com/railwayapp/cli/assets/70233964/3f95db84-7fdc-4355-8d99-85b3221bd698)

###  Detail

1.  First i was wondering, if the issue not coming from the protocol HTTP/HTTPS since the image are displaying with a TCP connection so with HTTP image are displaying
2. With a generate domain provide by railways the image are not displaying get the error from above and error 500 internal server error from the client 
3. Custom Domain same as step 2 

So i managed to fix this issue by adding in my next.config.js because in the error log, you can see about "imageOptimizer" but this solution, is not good and Image optimisation are requiered in my projet

```
const nextConfig = {
images: {
unoptimized: true,
},
  },
module.exports = `nextConfig;
```

ps : Let me know, if you need more information or if i miss something

**Comment by brody192** [comment]
Unfortunately this is not the correct place to open this kind of issue, I know you've already opened a help thread in the discord so that would be all that's needed!
