### ISSUE TITLE
Error: URL Not Found When Installing @railway/cli v3.4.0 

### ISSUE THREAD

**Issue by CamiloD16** [railwayapp/cli#454]
When attempting to install version v3.4.0 of @railway/cli using the `npm install -g @railway/cli` command, an error occurs due to the download URL for the binary not being available. The complete error message is as follows:

_https://github.com/railwayapp/cli/releases/download/v3.4.0/railway-v3.4.0-i686-pc-windows-gnu.tar.gz
Error: Failed fetching the binary: Not Found_

**Steps to Reproduce the Problem:**
1. I executed the `npm install -g @railway/cli` command on my system.
2. I encountered the aforementioned error.

**Additional Information:**
- Version of @railway/cli: v3.4.0
- Architecture: Ubuntu 64-bit
- npm version: 10.1.0

This issue is created to report the problem and request assistance in resolving it. I appreciate any guidance or solutions that can be provided.

**Comment by maddsua** [comment]
This should have been fixed by #389, which was 10 month ago, an it's still broken. Even the latest version (v3.5.2) still doesn't have files for the `i686-pc-windows-gnu` target.
Am I missing something?
