### ISSUE TITLE
railway shell not working

### ISSUE THREAD

**Issue by allestaire** [railwayapp/cli#462]
Can enter with `railway shell` command
I am using MacBook Air with terminal

Can someone point out why is this happening? or just railway didnt check this command if its working?

<img width="800" alt="Screen Shot 2023-10-23 at 9 20 23 AM" src="https://github.com/railwayapp/cli/assets/68372409/482ea837-5334-4e70-9377-e75f6b9dd7f0">

**Comment by allestaire** [comment]
This is bad, probabbly this service is not too active for feedbacks

**Comment by brody192** [comment]
@alexng353 when you have some time could you look into this? it seems like you have setup the code to spawn an interactive zsh shell perhaps?

**Comment by allestaire** [comment]
Is there a way to install a previous version of cli @brody192 ? 😄

**Comment by brody192** [comment]
> Is there a way to install a previous version of cli @brody192 ? 😄 

oh course, but the current code for the shell command has been present for quite a while now, going back wouldn't help, maybe `railway run` could work for you in the mean time? what was your usecase for shell?

**Comment by allestaire** [comment]
> > Is there a way to install a previous version of cli @brody192 ? 😄
> 
> of course, but the current code for the shell command has been present for quite a while now, going back wouldn't help, maybe `railway run` could work for you in the mean time? what was your usecase for shell?

OOhh, We are not able to use `railway run` thats why we tried to use `railway shell` but sadly both didnt work. We have to check whats on the service in order to configure and fix the issue regarding authentication of the app 😄

**Comment by brody192** [comment]
`railway shell` does not open up a shell into the deployment, railway does not provide any way to do that, `railway shell` opens up a local shell with the service variables available in the shell. this is divulging more into a help topic, so please feel free to open up a #Help thread in our server! [discord.gg/railway](https://discord.gg/railway)

**Comment by allestaire** [comment]
Hhmmm, base on what you have said, **variables available** in the shell, Im thinking is there a missing part when using `railway shell` does we need to add something variable on our shell in order for it to work?

**Comment by brody192** [comment]
no that's not the case, this is divulging more into a help topic, so please feel free to open up a #Help thread in our server! [discord.gg/railway](https://discord.gg/railway)

**Comment by alexng353** [comment]
> it seems like you haven't setup the shell code to spawn a zsh shell in interactive mode perhaps?

Thanks for the heads up I'll check it out when I get home.

**Comment by zuchka** [comment]
closing this. thanks all
