### ISSUE TITLE
[User Interview] railway up default behavior

### ISSUE THREAD

**Issue by JakeCooper** [railwayapp/cli#468]
## Suggestion

railway up - exit 0/1 for success/failed deploy
railway up --tail - holds for logs
railway up --detach - detaches immediately

## Why

This allows CI to actually invoke the CLI and pass the correct exit code to the CLI to pass/fail CI

**Comment by alexng353** [comment]
Good. Also allow user to globally set default (railway config --global up.finish=exit|tail|detach)

**Comment by brody192** [comment]
I would like the defaults to stay as they are, I don't think its a good idea to change the default behavior, additional behavior should be a flag, with that said I would like a `--wait` flag, wait for a the deploy to either fail or succeed, exits accordingly

**Comment by emilioschepis** [comment]
I'm also interested in this feature, I think it could be useful to have a good CI pipeline through services like GitHub Actions.

I don't know Rust that much, but I started working on a draft implementation for this. However looking at the subscription for build/deploy logs [here](https://github.com/railwayapp/cli/blob/68db247b67863e7d426d776ec516b0bb2cd1b8ac/src/controllers/deployment.rs#L62) I think that function will never return (it continuously waits on the next log).

Through the GraphiQL playground I also saw that there is no subscription for the deployment status, only a query (please correct me if I'm wrong) so I'm not really sure on how to approach this.

Thanks!

**Comment by brody192** [comment]
it would likely need to be achieved by polling for the deployment status, the same way that the dashboard does it

**Comment by maddsua** [comment]
That's literally what the cli currently does:
https://github.com/railwayapp/cli/blob/68db247b67863e7d426d776ec516b0bb2cd1b8ac/src/commands/up.rs#L336

**Comment by maddsua** [comment]
Guys I really wanna this resolved as it's one of those features that are not too hard to get done and it would greatly improve DX

**Comment by alexng353** [comment]
> Guys I really wanna this resolved as it's one of those features that are not too hard to get done and it would greatly improve DX

lol cli development is pretty slow right now. If you guys come to a resolution for how you want to do it, I will make some time to PR some changes.

**Comment by maddsua** [comment]
One more idea: we could add a little notification about default behavior being changed right into the cli. Also add a lil counter to show that for the first five runs only

**Comment by maddsua** [comment]
Also, most CICD envs set an env variable and we could detect that

**Comment by maddsua** [comment]
Anyway, here it is: #477

**Comment by mattrossman** [comment]
This would be very helpful for our CI/CD pipeline on GitLab. We have followed the official guide ["Using GitLab CI/CD with Railway"](https://blog.railway.app/p/gitlab-ci-cd) which recommends using the `-d` option on `railway up`, thus we always see jobs succeed in CI even when the build fails on Railway.

**Comment by maddsua** [comment]
#477 kinda solves this, we just need to decide on what to call the flag and we're basically done here

**Comment by mattrossman** [comment]
`railway up --ci` is short and sweet.

I'm coming from the Node.js ecosystem which has [`npm ci`](https://docs.npmjs.com/cli/v8/commands/npm-ci) (technically "clean install" but doubles as "continuous integration" in practice) and [`jest --ci`](https://jestjs.io/docs/cli#--ci) for precedent.

**Comment by maddsua** [comment]
Also can we please have a release so that I can finally use the damn docker image instead of running install script on each deploy? I could've just published the image myself, but having it not coming from railway will only complicate things down the road

**Comment by maddsua** [comment]
Guys, we can close this since it was resolved by #477 and #537
