### ISSUE TITLE
`railway up` will also ignore the `service-account.json` file, since `railway up` will respect the rules set in the `.gitignore` file.

### ISSUE THREAD

**Issue by alexng353** [railwayapp/cli#472]
`railway up` will also ignore the `service-account.json` file, since `railway up` will respect the rules set in the `.gitignore` file.
Could you download the file with a different filename?

_Originally posted by @brody192 in https://github.com/railwayapp/cli/issues/471#issuecomment-1830844324_
            
Proposal: Configuration flags and cascading `ignore` with priority
flags > .railwayignore > .gitignore

then, you can have a .railwayignore flag with `!service-account.json` inside it that cli respects when doing `railway up`

**Comment by zuchka** [comment]
@alexng353 can you please add this comment to the original thread? thanks!
