### ISSUE TITLE
Memory errors when I try to interact with ActiveRecord models

### ISSUE THREAD

**Issue by vmrocha** [railwayapp/cli#476]
# Scenario 1

When accessing any ActiveRecord via CLI.

```shell
$ railway run bin/rails console
Loading production environment (Rails 7.0.8)
irb(main):001> Person.count
ruby(64667,0x1d71c5000) malloc: double free for ptr 0x11e80a800
ruby(64667,0x1d71c5000) malloc: *** set a breakpoint in malloc_error_break to debug
$
```

# Scenario 2

When trying to run a rake tasks in a rail project, ruby crashes with the following error message:

```shell
$ railway run bin/rails user:send_birthdays_reminder
ruby(59032,0x1d71c5000) malloc: double free for ptr 0x139a1bc00
ruby(59032,0x1d71c5000) malloc: *** set a breakpoint in malloc_error_break to debug
$
```

That happens to any other task like `bin/rails db:migrate`. The command works fine if it is set as a startup command.

# Links

- [Discord discussion](https://discord.com/channels/713503345364697088/1189296003224961114)

**Comment by vmrocha** [comment]
What I'm getting as output on the observability tab:

```
no PostgreSQL user name specified in startup packet
```

**Comment by zuchka** [comment]
@vmrocha can you confirm that you're using this Rails template?

https://railway.app/template/sibk1f

**Comment by vmrocha** [comment]
Hi @zuchka ! No, I created the environment from scratch.

**Comment by zuchka** [comment]
still having trouble with this? if so, I'd recommend trying the Rails template we have and compare/contrast. That template is maintained in-house

**Comment by zuchka** [comment]
going to close this issue, but super happy to reopen once more info become available. 👍

**Comment by vmrocha** [comment]
Hi @zuchka, I don't have much information to provide. I don't think that rewriting my project from scratch based on the template could be an option, but I could try to check a diff between them. I will let you know if find something new. Thanks.

**Comment by Allerby** [comment]
Seeing the same thing here, however it's working on my machine when I access the railway shell and use rails console, however my colleague is seeing these malloc errors and we are seeing the same error ( FATAL:  no PostgreSQL user name specified in startup packet) pop into the observability panel. Did anyone here manage to find a fix/workaround?

We're using the same version of Railway CLI, and our system environments are a match as well.

**Comment by headmandev** [comment]
If you're using a Mac, this might help (it helped me in a similar situation)

```brew upgrade libpq```

https://stackoverflow.com/a/77558811/8831987
