### ISSUE TITLE
CLI still using legacy plugin-related commands / terminology

### ISSUE THREAD

**Issue by lucas-de-lima** [railwayapp/cli#480]
As you can see in the image, I need to do the command: railway add -p mysql to add the MySQL plugin to my project.
However, it asks to log in, says that I am not actorized, even though I have already logged in before.
I repeat Login and still receive the unauthorized message.
I tried other alternative commands for railway add, but to no avail.
(I don't know which data is really sensitive so I hid what I thought was best hidden.)

The image below has more details of what I tried to do.

I'm in the Ubuntu environment with WSL on Windows
latest version of railway installed

![Capturar03](https://github.com/railwayapp/cli/assets/108958270/eaeb21a5-9195-45c4-be79-fcead98d83e8)

**Comment by zuchka** [comment]
Hi! Thanks for submitting this. This does appear to be a bug. We recently changed the pattern for deploying databases on Railway. They are no longer plugins but services. I think the CLI will need to get updated to reflect this. "plugins" are no longer part of the Railway ecosystem. Instead we have "services"

**Comment by traconis** [comment]
This is happening with the railway add -p MySQL as well:
![image](https://github.com/railwayapp/cli/assets/862010/f8c23b6b-8095-456b-83e1-72a5197886a2)
Looks like railway cli is bugged totally :(

**Comment by Milo123459** [comment]
try running `railway link` and linking it to the service then see what happens please

**Comment by traconis** [comment]
Did all of that including copilot to fetch all related reddit/stackoverflow and github messages about that :) and trying everything. Somehow those self called "devs" assume everyone is on Linux/MacOS :DNever mind though, I changed the provider.Thanks for your time even looking at my comment.TomaszTemat: Re: [railwayapp/cli] CLI still using legacy plugin-related commands / terminology (Issue #480)Data: 2024-04-21 16:06Nadawca: "Milo" ***@***.***&gt;Adresat: "railwayapp/cli" ***@***.***&gt;; DW: "traconis" ***@***.***&gt;; "Comment" ***@***.***&gt;; 

try running railway link and linking it to the service then see what happens please
