### ISSUE TITLE
[Feature Request] Add `[skip cd]` in commit messages to make Railway skip deployment on that commit

### ISSUE THREAD

**Issue by championswimmer** [railwayapp/cli#483]
On most CI systems, adding `[skip ci]` in the commit message skips running tests / builds on that commit. 

Sometimes I want to 
- run buid/tests
- but not make a fresh deployment on railway

An example scenario could be when I make improvements to only the tests, but not add actual functioanlity 

Can I use `[skip cd]` in the commit message, and Railway will ignore that commit for deployment?

**Comment by Milo123459** [comment]
this hasn't got anything to do with the cli it seems, `railway up` is the only way to make deployments from the cli
