### ISSUE TITLE
What happened to the .deb artifacts?

### ISSUE THREAD

**Issue by raxod502** [railwayapp/cli#494]
Hi, my system upgrade tooling failed recently because `.deb` packages are no longer being published on GitHub Releases. There was one for 3.5.2 but none for 3.7.0. I looked for documentation in the README about the change, and for a CHANGELOG (couldn't find either). I also didn't see anything that looked relevant in the commit messages between those tags, maybe I missed something. Is this intentional?

**Comment by aleksrutins** [comment]
Looks like the release build [failed](https://github.com/railwayapp/cli/actions/runs/8710814988/job/23893531200). I'll look and see if I can figure it out, otherwise I'll raise it to someone with more experience in this codebase.
