### ISSUE TITLE
Suggestion: Allow `node_modules` to be included in deployments with `railway up`

### ISSUE THREAD

**Issue by mikebywaters** [railwayapp/cli#496]
## Problem

`railway up` ignores `node_modules` by default:
https://github.com/railwayapp/cli/blob/2d2a8c14385368662059e2781c4d2412aef419a9/src/commands/up.rs#L184C34-L184C46
but there are use cases where deploying the contents of `node_modules` is desirable, eg. when the dependency install is being done as part of another CI pipeline (eg. GitHub Actions, Buildkite) and isn't part of the Docker container. 

## Potential solutions

1. Remove the default behaviour
2. Provide a flag that enables the behaviour to be bypassed

**Comment by maddsua** [comment]
Hey @mikebywaters!
Just yesterday we got the CLI image published to ghcr. Now you can build everything inside of CI environment of your choice and then push the result to railway with a minimal dockerfile or nix config
