### ISSUE TITLE
Add CLI feature for adding a custom domain

### ISSUE THREAD

**Issue by jph00** [railwayapp/cli#512]
It would be helpful to have something in the CLI to allow us to add a custom domain. AFAICT current `railway domain` only adds an internal one. I'd like to be able to automate the process of attaching a custom domain.

**Comment by JakeCooper** [comment]
I'm happy to throw a community bounty up on this one for $100. Payable via GH sponsors/BMAC/etc

**Comment by Mihir867** [comment]
Hey, Can you assign this to me ?

**Comment by JakeCooper** [comment]
I think this can go to whoever has a working PR setup for it. Happy to pay out whoever
