### ISSUE TITLE
`railway up --ci` doesn't wait for build to finish in GitLab CI/CD

### ISSUE THREAD

**Issue by mattrossman** [railwayapp/cli#517]
The goal of `railway up --ci` from #477 is to allow you to wait for the build to succeed or fail in a CI environment such as GitLab CI/CD.

The command behaves as expected when running locally on my MacBook.
I see build logs streaming in and it ends with a `Deploy complete` message when the service is actually live on Railway.
<img width="222" alt="CleanShot 2024-06-25 at 10 51 33@2x" src="https://github.com/railwayapp/cli/assets/22670878/b1083a86-38b7-4b9c-9932-63671b3a4518">

When I use the same flag in GitLab CI/CD however, the pipeline exits after upload is complete and a link to the build logs is shown. It effectively behaves the same as it used to with the `--detach` flag.

<img width="700" src="https://github.com/railwayapp/cli/assets/22670878/b8d88d88-4e87-4152-b0a1-c33701f28de3" />

I verified that both my MacBook and the GitLab runner are using the latest Railway CLI version `3.9.3` by running `railway --version` (see output from GitLab CI in pic above).

The `gitlab-ci.yml` pipeline is based on the official guide [Using GitLab CI/CD with Railway](https://blog.railway.app/p/gitlab-ci-cd), only difference is I changed `-d` to `--ci`

**Comment by maddsua** [comment]
This issue can be closed now as the problem has been fixed in #537
