### ISSUE TITLE
[Feature Request] Support for Account-Level API Tokens for authenticating Railway CLI

### ISSUE THREAD

**Issue by aryanprince** [railwayapp/cli#538]
# Summary

The Railway CLI currently **only supports project-level API tokens** for authentication but **does not support account-level API tokens**. Adding support for account-level tokens would enable integration with tools like the [1Password Shell Plugin](https://developer.1password.com/docs/cli/shell-plugins), allowing for easy (and secure) authentication across multiple projects when using the CLI locally.

## What's the problem

When using a project-level API token, commands like the following work as expected:

```sh
RAILWAY_TOKEN="my_project_level_api_token" railway run
```

However, the CLI does not support account-level API tokens. If attempted:

```sh
RAILWAY_TOKEN="my_account_level_api_token" railway run
```

The command fails, limiting authentication to single-project tokens only.

## Potential solution

Allow the Railway CLI to accept account-level API tokens, so commands like:

```sh
RAILWAY_TOKEN="my_account_level_api_token" railway whoami
# or
RAILWAY__ACCOUNT_TOKEN="my_account_level_api_token" railway whoami
```

return the user’s account details! ✨

## Reference

This feature would improve compatibility with tools like 1Password's CLI Shell Plugin. See the related issue on 1Password's open-source shell plugin repo [here](https://github.com/1Password/shell-plugins/issues/151).

**Comment by brody192** [comment]
Unless I'm massively misunderstanding your feature request.. The CLI already supports using an account token via `RAILWAY_API_TOKEN`

https://github.com/railwayapp/cli/blob/master/src/config.rs#L115
