### ISSUE TITLE
Railway login fails, no logic

### ISSUE THREAD

**Issue by bobir01** [railwayapp/cli#553]
<img width="475" alt="image" src="https://github.com/user-attachments/assets/6a9fc3da-20fa-4dd5-9e20-fa3e797de180">

it makes login impossible
version: `railwayapp 3.15.1`
macos: `Sonama`
installed with curl official link in website

**Comment by andtos90** [comment]
Version `3.14.0` works fine. As a temporary workaround:

- Remove Railway CLI
- Run `npm install -g @railway/cli@3.14.0`

**Comment by agileben** [comment]
Yeah ran into this. npm install -g @railway/cli@3.14.0 fixed it

**Comment by himself65** [comment]
<img width="442" alt="image" src="https://github.com/user-attachments/assets/65cff961-9b7d-4336-b9e9-73d9707c6d13">

Error still here

**Comment by brody192** [comment]
Please see the linked PR, once merged and released this issue will be solved.
