### ISSUE TITLE
Legacy Runtime Build Failures

### ISSUE THREAD

**Issue by GrantBirki** [railwayapp/cli#581]
Suddenly, builds are failing when using the `legacy` runtime option for our service with the following logs:

```text
The selected runtime: UNSPECIFIED is not supported in this region: us-west2.
You can update the runtime in your service settings
```

We have not made any changes to our service and these errors started occurring on fresh builds. By simply upgrading from the `legacy` runtime to `v2`, this error resolved itself. Here is an example of all the failed builds, followed by a successful one:

![Image](https://github.com/user-attachments/assets/a0545e84-345a-43a0-b506-f42c008190df)

After upgrading to the `v2` [runtime](https://docs.railway.com/reference/runtime), things are working again. However, this is a bit frightening to have builds suddenly break without any changes. Furthermore, after upgrading to `v2`, the option in the UI has disappears to go back to `legacy` if something goes amiss.

Project ID: `3bfd2b23-234e-489d-968e-71f55bbe7092`

Project source code: (its open source 😉) https://github.com/the-hideout/stash

cc: @coffee-cup for visibility

**Comment by GrantBirki** [comment]
After migrating to the `v2` runtime from `legacy`, it also looks like significantly more CPU usage is occurring. We went from an average of `0.2` vCPU to now `0.6` vCPU. This will directly correlate to an almost 200% increase in our spend on railway 😬.

![Image](https://github.com/user-attachments/assets/c95599c0-340e-4e8d-8c17-5402fb1fc77d)

**Comment by GrantBirki** [comment]
I did some digging and found that you can force set the `runtime` back to `LEGACY` by using the _Config as Code_ feature even though the option disappeared in the UI.

Here is a commit showing how I did this: https://github.com/the-hideout/stash/pull/331/commits/185ec3452866f14e9700d900babf6c74fc94e41b

However, this resulted in a failed deployment with the following logs:

```text
The selected runtime: LEGACY is not supported in this region: us-west2.
You can update the runtime in your service settings
```

I don't recall ever changing the region to `us-west2`, especially since it is listed as a `beta` region for metal.

![Image](https://github.com/user-attachments/assets/4b18be9c-764b-4cc8-99e2-fa9070727bf1)

> Railway's docs showing `us-west2` clearly marked as a beta region for metal.

The solution I took was choosing a standard non-metal/non-beta region. This ended up being `us-west1`: https://github.com/the-hideout/stash/pull/331/commits/6710ad1cba4da87c297f82be018371854049c7e1

I also had to update the value for the region under the main config of the service before I could branch deploy changes:

![Image](https://github.com/user-attachments/assets/0460fb11-65c8-4b6f-aeb6-8da65a404e90)

**Comment by GrantBirki** [comment]
After going back to the `LEGACY` runtime, CPU measurements have dropped back to their normal levels:

![Image](https://github.com/user-attachments/assets/0c5211c0-ba58-4916-adad-bec732492858)

**Comment by brody192** [comment]
Hey,

Going to close this as this issue has nothing to do with the CLI.

For help with these kinds of things, please use the proper channels - https://help.railway.com/

Additionally, I can not recommend you force the runtime to Legacy, it's Legacy for a good reason and will be fully removed as an option regardless of where the runtime is set.

Best,
Brody
